### ISSUE TITLE
Code 4 feedback

### ISSUE THREAD

**Issue by bigfatnoob** [gbtimmon/ase16GBT#3]
The optimal solution for SA on Schaffer is at x=1. But you seem to have got a very large optimum(x=84018). Please check your code and try rectifying this error. If you have trouble understanding SA, come talk to me. Close when this is completed

**Comment by MichaelGoff** [comment]
Modified to minimize energy in 3d8b6c4

**Comment by bigfatnoob** [comment]
Can you submit the new output image

**Comment by MichaelGoff** [comment]
New image committed 8ae238b
